"""email verification and password reset

Revision ID: 5ffefc9b98ac
Revises: 79379432f74d
Create Date: 2026-07-27 14:54:18.426330
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '5ffefc9b98ac'
down_revision: str | None = '79379432f74d'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tokens'))
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_verification_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_verification_user_purpose', ['user_id', 'purpose'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_user_purpose')
        batch_op.drop_index(batch_op.f('ix_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_token_hash'))

    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
